# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_consulta',
            fields=[
                ('Id_Motivo', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Motivo_consulta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_paciente', models.IntegerField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=35)),
                ('Apellido', models.CharField(max_length=35)),
                ('EPS', models.CharField(max_length=35)),
                ('Genero', models.CharField(max_length=35)),
                ('Email', models.EmailField(max_length=35)),
                ('Municipio', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='motivo_consulta',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
    ]
