# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad_Actual',
            fields=[
                ('Id_Enfermedad', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Enf_actual', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='motivo_consulta',
            name='Motivo_consulta',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='enfermedad_actual',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
    ]
