# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0002_auto_20171108_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('Id_antecedentes', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Patologicos_medicamentos', models.CharField(max_length=50)),
                ('Toxicos_alergicos', models.CharField(max_length=50)),
                ('Quirurgicos', models.CharField(max_length=50)),
                ('Trau_fisicos', models.CharField(max_length=50)),
                ('Trau_emocionales', models.CharField(max_length=50)),
                ('Habitos_saludables', models.CharField(max_length=50)),
                ('Habitos_riesgo', models.CharField(max_length=50)),
                ('Familiares', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('Id_diag_CIE10', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosticos_propios',
            fields=[
                ('Id_diagnostico', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Nombre_diag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Examen_Fisico',
            fields=[
                ('Id_examen', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('TA', models.IntegerField()),
                ('FC', models.IntegerField()),
                ('FR', models.IntegerField()),
                ('Peso', models.IntegerField()),
                ('Estatura', models.IntegerField()),
                ('Perimetro_cintura', models.IntegerField()),
                ('IMC', models.IntegerField()),
                ('Pulso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gustos_preferencias',
            fields=[
                ('Id_Gustos', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Clima', models.CharField(max_length=50)),
                ('Temperatura', models.CharField(max_length=50)),
                ('Colores', models.CharField(max_length=50)),
                ('Numeros', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medidas_antropometricas',
            fields=[
                ('Id_medidas', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Organo', models.CharField(max_length=50)),
                ('Clasificacion', models.CharField(max_length=50)),
                ('Especificacion', models.CharField(max_length=50)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.Examen_Fisico')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_manejo',
            fields=[
                ('Id_plan', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Plan_manejo', models.CharField(max_length=50)),
                ('Control', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Examen',
            fields=[
                ('Id_resultado', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rev_sistemas',
            fields=[
                ('Id_revision', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Rev_consulta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Terapias',
            fields=[
                ('Id_terapia', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Terapia', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Especificaciones', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='terapias',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='rev_sistemas',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='resultado_examen',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='plan_manejo',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='gustos_preferencias',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='diagnosticos_propios',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
        ),
    ]
