# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0003_auto_20171108_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('Id_usuario', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
