# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0006_auto_20171113_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_manejo',
            old_name='Plan_manejo',
            new_name='Plan',
        ),
    ]
