# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0007_auto_20171213_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidas_antropometricas',
            old_name='id_examen',
            new_name='Id_examen',
        ),
    ]
