# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0008_auto_20171213_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paraclinicos',
            fields=[
                ('Id_paraclinico', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Diagnostico', models.CharField(max_length=500)),
                ('Medicamentos', models.CharField(max_length=500)),
                ('Incapacidad', models.CharField(max_length=500)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente')),
            ],
        ),
    ]
