# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0009_paraclinicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paraclinicos',
            name='id_paciente',
        ),
    ]
