# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0010_remove_paraclinicos_id_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraclinicos',
            name='id_paciente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente'),
            preserve_default=False,
        ),
    ]
