# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0012_auto_20180109_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Direccion',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='Estado_civil',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='Ocupacion',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='Religion',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='Telefono',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
