# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0013_auto_20180220_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Ano',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='Dia',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='Mes',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enfermedad_actual',
            name='Enf_actual',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='motivo_consulta',
            name='Motivo_consulta',
            field=models.CharField(max_length=800),
        ),
    ]
