# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0014_auto_20180227_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_fisico',
            name='Abdomen',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Aspecto_general',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Cabeza',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Cardiopulmonar',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Cavidad_oral',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Cuello',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Extremidades',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Genitourinario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Neurologico',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Osteomuscular',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='Piel',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
