# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0015_auto_20180227_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gustos_preferencias',
            name='Clima',
        ),
        migrations.RemoveField(
            model_name='gustos_preferencias',
            name='Colores',
        ),
        migrations.RemoveField(
            model_name='gustos_preferencias',
            name='Numeros',
        ),
        migrations.RemoveField(
            model_name='gustos_preferencias',
            name='Temperatura',
        ),
        migrations.AddField(
            model_name='gustos_preferencias',
            name='Gustos',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Email',
            field=models.CharField(max_length=35),
        ),
    ]
