# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0018_auto_20180301_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paraclinicos_aportados',
            name='id_paciente',
        ),
        migrations.DeleteModel(
            name='Paraclinicos_aportados',
        ),
    ]
