# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0019_auto_20180302_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Para_aportados',
            fields=[
                ('Id_Aporte', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Para_aportados', models.CharField(max_length=800)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historiaclinica.paciente')),
            ],
        ),
    ]
