# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0022_auto_20180302_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticos_propios',
            name='id_paciente',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='Id_diag_CIE10',
            new_name='Id_diag',
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='Tipo',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='Nombre_diag',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Diagnosticos_propios',
        ),
    ]
