# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0023_auto_20180302_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_fisico',
            name='Energia',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Abdomen',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Aspecto_general',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Cabeza',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Cardiopulmonar',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Cavidad_oral',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Cuello',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Extremidades',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Genitourinario',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Neurologico',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Osteomuscular',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='Piel',
            field=models.CharField(max_length=500),
        ),
    ]
