# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0027_auto_20180308_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_CIE10',
            fields=[
                ('Id_tabla_CIE10', models.AutoField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('Cod_nombre', models.CharField(max_length=80)),
            ],
        ),
    ]
