# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiaclinica', '0028_tabla_cie10'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla_CIE10',
        ),
    ]
